#!/bin/bash

MAIN_JS=scripts.js

EXCLUDE_FILES='lang.js lang.min.js'


# js uglify
cd assets/js/

rm ${MAIN_JS}

echo 'Bundling up the JavaScripts...'

for file in *.js
do
	if [[ "${MAIN_JS} ${MAIN_JS%.*}.min.js ${EXCLUDE_FILES}" =~ "${file}" ]]; then
		continue
	fi
	(cat ${file};echo) >> ${MAIN_JS}
done

exit 0
