#!/bin/bash

echo 'Uglifying the JavaScripts...'

cd assets/js/

for file in _*[^.min].js; do
	
	if [[ ${file} == _* ]]; then
		OUTPUT_FILE=${file#"_"}
	else
		OUTPUT_FILE=${file}
	fi

	OUTPUT_FILE="${OUTPUT_FILE%.*}.min.js"

	terser ${file} --compress --mangle > "${OUTPUT_FILE}"
done

terser ${MAIN_JS} --compress --mangle > "${MAIN_JS%.*}.min.js"

cd ${OLDPWD} > /dev/null