#!/bin/bash

echo 'Start building script...'

CMD_BUILD="JEKYLL_ENV=production bundle exec jekyll build 2> /dev/null"

# Javascripts

export MAIN_JS=scripts.js

## Bundle Javascripts
source _bin/bundlify

## UglifyJS
source _bin/uglify


# Build

echo 'Jekyll building...'

eval "${CMD_BUILD}"


# Critical for CSS

#echo "Doing the Critical CSS..."

# cd _site
# for file in $(find ./ -type f -name '*.html'); do
# 	_FILE=`cat ${file}`
# 	echo "$_FILE" | critical --base ./ --folder "`dirname ${file}`/" --inline > ${file}
# done


exit 0
